version: '3.8'

services:
  mongo_db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - creditapproval_js

  backend_js:
    build: .
    command: >
      sh -c "npm install && npm start"
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/creditapprovalmono
    depends_on:
      - mongo_db
    networks:
      - creditapproval_js

volumes:
  mongo_data:

networks:
  creditapproval_js:
    driver: bridge